### ISSUE TITLE
Allow clicking a username when viewing a guide to nav to a creator's page

### ISSUE THREAD

**Issue by RjDrury** [jensbuehl/aoe4-guides#102]
When viewing a guide, I want to see what other guides the user has made.

I would like to make their username that appears here to be clickable

![image](https://github.com/user-attachments/assets/f3f9079f-975b-472e-9fd1-718ad73ef0b5)

**Comment by jensbuehl** [comment]
Good suggestion, thanks for the feedback!

**Comment by jensbuehl** [comment]
Introduced in:
12001e28b283f18d444d218b9a1b868df9198fd5
