### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by LENpolygon** [jensbuehl/aoe4-guides#59]
Hi Jens, 

Just dropping by to let you know that this tool is shaping out to be the perfect aoe4 build order tool!
The new addition of using the icons in the guides is something I'm a huge fan of and your implementation looks great.

Keep up the awesome work!!

Best regards,
Len

**Comment by jensbuehl** [comment]
Thanks, Len!
You inspired me a lot - I just wanted to overcome a few limitations of age4builder and learn vue.
Feel free to join in. Help is always appreciated. Especially considering the maintenance after each season. :)
