### ISSUE TITLE
Error with import build & villager otto icon

### ISSUE THREAD

**Issue by HubSiteski** [jensbuehl/aoe4-guides#72]
When i try to save imported build it shows this error on screenshot
and
@unit_worker/villager-ottomans.png@ doesn't show icon of villager but @unit_worker/villager.png@ works

![image](https://github.com/jensbuehl/aoe4-guides/assets/115024812/27dbb568-f999-48ee-9902-0c622962264c)

**Comment by jensbuehl** [comment]
Thx for the feedback.
Could you please attach the corresponding file that you are trying to import?

Then I could try to reproduce and take a look.

**Comment by jensbuehl** [comment]
PS: regarding the villager icon. This is a limitation of the overlay tool which only supports the generic villager icon but not the civ specific ones. We could try to push a change request there.

It's a matter of adding the missing ottoman file.

**Comment by jensbuehl** [comment]
I tested it with this build order file from ebodur and it works fine.
So we have to check your specific file and see what might be different or missing.
[[Beastyqt] Mehter archers.txt](https://github.com/jensbuehl/aoe4-guides/files/11673223/Beastyqt.Mehter.archers.txt)

**Comment by jensbuehl** [comment]
Did it work meanwhile?
I see your BO here:
https://aoe4guides.com/builds/ri6UPPNR2b2k1OiIhnMT

**Comment by jensbuehl** [comment]
Closed since no response and not reproducable.
