### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by SebastianEShelby** [jensbuehl/aoe4-guides#73]
Please add a light mode to the website

**Comment by jensbuehl** [comment]
Update: Working on it

**Comment by jensbuehl** [comment]
Published. See here: https://www.reddit.com/r/aoe4/comments/15b0zpx/villager_of_the_day_light_theme_and_more_update/

**Comment by SebastianEShelby** [comment]
> Published. See here: https://www.reddit.com/r/aoe4/comments/15b0zpx/villager_of_the_day_light_theme_and_more_update/

Thanks for the update! There isn't enough contrast between the text and background colors in the light theme. I would suggest setting the default to dark theme for better accessibility.

**Comment by jensbuehl** [comment]
Oh, just noticed the message.
I updated the light theme meanwhile.

You can force dark mode at any time via browser or system settings, though.
________________________________
Von: Sebastian Shelby ***@***.***>
Gesendet: Sonntag, 6. August 2023 16:20
An: jensbuehl/aoe4-guides ***@***.***>
Cc: Jens ***@***.***>; State change ***@***.***>
Betreff: Re: [jensbuehl/aoe4-guides] Light mode (Issue #73)


Published. See here: https://www.reddit.com/r/aoe4/comments/15b0zpx/villager_of_the_day_light_theme_and_more_update/

Thanks for the update! There isn't enough contrast between the text and background colors in the light theme. I would suggest setting the default to dark theme for better accessibility.
