### ISSUE TITLE
Season 6 update for AoE4/RTS Overlay

### ISSUE THREAD

**Issue by CraftySalamander** [jensbuehl/aoe4-guides#74]
Hi.
I see that you already updated aoe4guides.com with Season 6 content, including the 6 new civs.
Nice :-)

Do you plan to make pull requests on AoE4/RTS Overlay, or should I do this?
For the second option, could you tell me when the assets of Season 6 are final (I see that the branch is not yet merged and that you pushed new commits 1 hour ago).

**Comment by CraftySalamander** [comment]
Hey.
I already released the release 1.7.1 on RTS Overlay (see [here](https://github.com/CraftySalamander/RTS_Overlay/commit/7035a670f9c82f394d595e3139c157847609d980)).

I also prepared the pull request for Maguro [here](https://github.com/FluffyMaguro/AoE4_Overlay/pull/29) (AoE4 Overlay).
Could you review it?

**Comment by CraftySalamander** [comment]
It is merged, thank you for the review.

**Comment by jensbuehl** [comment]
Sorry, I just saw that message a bit late.
Busy time here with the children. Sorry!

But meanwhile, you updated it already, right?
The images are final now.
________________________________
Von: CraftySalamander ***@***.***>
Gesendet: Donnerstag, 16. November 2023 09:29
An: jensbuehl/aoe4-guides ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [jensbuehl/aoe4-guides] Season 6 update for AoE4/RTS Overlay (Issue #74)


Hi.
I see that you already updated aoe4guides.com with Season 6 content, including the 6 new civs.
Nice :-)

Do you plan to make pull requests on AoE4/RTS Overlay, or should I do this?
For the second option, could you tell me when the assets of Season 6 are final (I see that the branch is not yet merged and that you pushed new commits 1 hour ago).

**Comment by CraftySalamander** [comment]
Yes, this is the PR you reviewed last weekend.
Courage with the kids (same situation here ^^) !
