### ISSUE TITLE
Add Ability to Type Icons via Shorthand

### ISSUE THREAD

**Issue by erin-fitzpatric** [jensbuehl/aoe4-guides#75]
When typing within text fields, add the ability to type an icon based off an assigned shortcut. Instead of pulling up the icon drop-down and manually picking an icon, type something like :vill to automagically insert the villager icon.

This would greatly speed up input process and make the tools easier to adapt. It also seems like the icons don't load very quickly when using the button to insert one. Perhaps this can be optimized?

**Comment by jensbuehl** [comment]
Thanks! Good suggestion.

I had a similar idea right from the start, but since this is my first web project, I was simply lacking the skills and time to prepare and so went for the easier way that does not involve input parsing. ;)

Same is true for the optimization. I guess, I would have to pre-load the images in the background and cache.

Feel free to get involved.
With 2 kids around, I cannot promise when I will find the time for any of the suggestions.

**Comment by jensbuehl** [comment]
PS: Found out that it seems to be the vuetify layouter which eats up a lot of time every time you open up the icon selector. Not the images. This icon selector needs optimization, I agree!

**Comment by jensbuehl** [comment]
For future reference:
https://www.reddit.com/r/vuetifyjs/s/KfSOirk3O7

**Comment by erin-fitzpatric** [comment]
Mind hitting me up on Discord? I cloned the repo locally and wanted to poke around but not sure how to locally dev against the cloud resources being leveraged. My name is: fitzbro

**Comment by jensbuehl** [comment]
Sure, once the kids are in bed. Most likely you just need to create an app key to access the dev environment on firebase. 

I did some testing on a local branch reg. inline shortcut replacement. Is doable. Cursor placement needs to be solved, though.

**Comment by jensbuehl** [comment]
This seems to be a good inspiration for autocomplete:
https://medium.com/streak-developer-blog/the-complexities-of-implementing-inline-autocomplete-for-content-editables-e358c0ed504b

**Comment by jensbuehl** [comment]
implemented in today's release (no autocomplete menu, though)
- improved icon selector performance
- add icons by shorthand or partial title match inline
