### ISSUE TITLE
Multi-line problem in firefox

### ISSUE THREAD

**Issue by schwazza** [jensbuehl/aoe4-guides#77]
BO created with Firefox have problems with line breaks and therefore also with the overlay tool.

BO created with Firefox:
![grafik](https://github.com/jensbuehl/aoe4-guides/assets/67942392/f367954f-d803-4408-a81c-a3b73612a082)

Same BO created with Chrome:
![grafik](https://github.com/jensbuehl/aoe4-guides/assets/67942392/36cacd2c-28e0-4640-a40d-4f2e6a9fc9d9)

The "Copy to Clipboard"-Button also doesnt work in Firefox:
![grafik](https://github.com/jensbuehl/aoe4-guides/assets/67942392/d3c7b3de-a360-4d83-9548-3cdc0cdf17a9)

**Comment by jensbuehl** [comment]
The <ENTER> behavior should be the same in all browsers in the next version. But still needs to be tested 😉

The "Copy to Clipboard" problem cannot be solved in Firefox:
"Firefox currently doesn't allow web pages to access the clipboard via JavaScript, so your only option would be to use the keyboard."
Workaround: 
Use a different browser or download BO as a file and then copy it...

**Comment by jensbuehl** [comment]
fixed in today's release
