### ISSUE TITLE
colon as stand alone sign

### ISSUE THREAD

**Issue by schwazza** [jensbuehl/aoe4-guides#80]
Is it possible to use colon as `:` and not as start symbol for autocomplete?
For me it seems impossible to insert a simple colon.
Is there some kind of workaorund?
Maybe colon followed by blank leads to `:`

**Comment by jensbuehl** [comment]
I will put it on the list. I agree that this needs improvement.

Maybe even simpler would be using a different activator chatacter that had no conflicts.

**Comment by jensbuehl** [comment]
I went for the easy way and introduced "::" as activator to prevent interfering with the regular ":"
Otherwise it causes quite a headache to distiguish between "intended text colon" and "autocomplete colon" with all edge cases.

Fixed and published in version 1.6.10.
