### ISSUE TITLE
Dont export empty time line

### ISSUE THREAD

**Issue by schwazza** [jensbuehl/aoe4-guides#81]
Most of my build orders I use in combination with the overlay tool.
Therefore I try to save as much space on the screen as possible.
If I'm not using the time column
![image](https://github.com/jensbuehl/aoe4-guides/assets/67942392/25a2ec44-0aa3-4b23-9741-69279aed7b71)
 it will be exported as `"time": "<br>"`.
This leads to a clock symbol and a wider view in the overlay tool.
It sill works if I delete the empty `"time": "<br>"`, line in the .json-file which removes the clock symbol.
Is it possible not to export the empty line at all?

**Comment by schwazza** [comment]
The problem only seems to occur if you have previously duplicate a build.

For exampe:
https://aoe4guides.com/builds/Efhok4VWHsgzl8lb7dsC

This is not the case if the BO have been created from scratch.

**Comment by jensbuehl** [comment]
Thx. Will take a look and prevent empty exports.
It's on the backlog now. However, time constraints might delay the improvement.

**Comment by jensbuehl** [comment]
It was just a one-liner. Fixed and published in version 1.6.10.
