### ISSUE TITLE
Adding  Collect Tax & Supervise for Imperial Officers

### ISSUE THREAD

**Issue by schwazza** [jensbuehl/aoe4-guides#85]
Sometimes its important to supervise for example the mill.
Therefore it would be nice to add the ability icon on aoe4guides.com and for the OverlayTool.

**Comment by jensbuehl** [comment]
Good one. Thanks for reporting.
I'll lookup the icon when I find time and add it.
OverlayTool is out of my hands. But let's inform them once it's available on aoe4guides.

**Comment by jensbuehl** [comment]
Do you know which color it has in-game? (violet like JD abilities? or green like techs?)
![image](https://github.com/jensbuehl/aoe4-guides/assets/3983913/65d4f519-e11c-457d-b72b-60b6cf5b975c)

**Comment by jensbuehl** [comment]
I have added it on aoe4guides.
