### ISSUE TITLE
Indicator for comments

### ISSUE THREAD

**Issue by schwazza** [jensbuehl/aoe4-guides#86]
![grafik](https://github.com/jensbuehl/aoe4-guides/assets/67942392/50e9c4c7-30a2-4cb5-bcb7-aa396f331cfe)

I never know if there is a comment on one of my BO.
Maybe its possible to add a small number + indicator like ![grafik](https://github.com/jensbuehl/aoe4-guides/assets/67942392/691d98b5-e5f2-4fb0-aaca-3080a1ea99dd) next to the overview in the image above.

I think comments are quite rare, so maybe the indicator shuold only appear after the first comment.

**Comment by jensbuehl** [comment]
Good suggestion. Somewhat related to "email notification on comments" #66 
I will put it in the backlog.

**Comment by jensbuehl** [comment]
Implemented in [v1.7.6](https://github.com/jensbuehl/aoe4-guides/tree/v1.7.6)

![image](https://github.com/jensbuehl/aoe4-guides/assets/3983913/7248f268-19b0-4222-a85a-fc1440e20b46)
