### ISSUE TITLE
"My favorites" shows own builds instead of bookmarked builds

### ISSUE THREAD

**Issue by Sharptsa** [jensbuehl/aoe4-guides#87]
Since the new update, the "Favorites" page doesn't show my favorite builds but the builds I created instead. ("My builds" page works as expected)

**Comment by jensbuehl** [comment]
Thanks for reporting. I am on it and will publish soon!

**Comment by jensbuehl** [comment]
I have just pushed a hotfix b3b4188 
Give it a try.

The last update was rather big under the hood. So some issues slipped through...

**Comment by Sharptsa** [comment]
Works like a charm, thanks for the quick fix and the great project as a whole 👍
