### ISSUE TITLE
Cachin problem. Only old Civs.

### ISSUE THREAD

**Issue by bylmzio** [jensbuehl/aoe4-guides#92]
I dont know what is causing this problem, but it seems on every first visit of the page i dont see all civs and icons.
After Hard-Reload it works. Until closing the browser.
![grafik](https://github.com/jensbuehl/aoe4-guides/assets/7440674/1cb4c1d0-406d-4cfe-9d9c-a0a2d04ec8e6)
![grafik](https://github.com/jensbuehl/aoe4-guides/assets/7440674/fe3f5634-8636-426b-8369-9c65d7400119)

**Comment by bylmzio** [comment]
Firefox 127.0.2 (64-Bit). Windows and Mac

**Comment by jensbuehl** [comment]
Clear browser cache in general and see if it persists?

**Comment by jensbuehl** [comment]
Assuming that clearing the overall browser cache fixed the issue. I did not hear anything similar from other users.
Closed.
