### ISSUE TITLE
Feature Idea: Screen Awake Lock for Focus mode

### ISSUE THREAD

**Issue by mornir** [jensbuehl/aoe4-guides#95]
Hi! Thanks for this website!
When using the focus mode while playing, the screen keeps dimming and turning off. I suggest keeping the screen awake using the WakeLock API (https://developer.mozilla.org/en-US/docs/Web/API/WakeLock).
From what I've read, it should be quite easy to implement. Closing the focus mode would release the lock.

(I could also make a pull request. I've cloned the repo, but struggle with adding new users locally after I created my own firebase project. I get the error `Could not signin: auth/network-request-failed`)

**Comment by jensbuehl** [comment]
Thx for your feedback.
Good idea, will give it a shot when time permits. (or take a look at your PR)

I guess you do not need a whole new firebase environment, I already have a dev and prod project in place.
All you need should be a debug token (for app-check), and proper local .env file for the dev environment.
I could provide you with this if I find time. 😄 Just ping me on discord.


________________________________
Von: Jérôme Pott ***@***.***>
Gesendet: Samstag, 24. August 2024 15:32
An: jensbuehl/aoe4-guides ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [jensbuehl/aoe4-guides] Feature Idea: Screen Awake Lock for Focus mode (Issue #95)


Hi! Thanks for this website!
When using the focus mode while playing, the screen keeps dimming and turning off. I suggest keeping the screen awake using the WakeLock API (https://developer.mozilla.org/en-US/docs/Web/API/WakeLock).
From what I've read, it should be quite easy to implement. Closing the focus mode would release the lock.

(I could also make a pull request. I've cloned the repo, but struggle with adding new users locally after I created my own firebase project. I get the error Could not signin: auth/network-request-failed)

**Comment by jensbuehl** [comment]
Since I am already familiar with  vueuse, I'll try this:
https://vueuse.org/core/useWakeLock/

**Comment by jensbuehl** [comment]
Integrated with the latest release, give it a try!
